
const $=(s,root=document)=>root.querySelector(s);const $$=(s,root=document)=>[...root.querySelectorAll(s)];
const saved=localStorage.getItem('theme');if(saved)document.documentElement.dataset.theme=saved;
$('#themeToggle')?.addEventListener('click',()=>{const cur=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=cur;localStorage.setItem('theme',cur)});
$('#hamb')?.addEventListener('click',e=>{const m=$('#menu');m.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',m.classList.contains('open'))});
window.addEventListener('scroll',()=>{const h=document.documentElement;const p=h.scrollTop/(h.scrollHeight-h.clientHeight)*100;const bar=$('#progress');if(bar)bar.style.width=p+'%'});
const words=['Customers','Teams','Growth','Automation','Insights','Launches'];let wi=0,ci=0,del=false;function type(){const el=$('#type');if(!el)return;const w=words[wi];el.textContent=w.slice(0,ci);ci+=del?-1:1;if(ci>w.length+8)del=true;if(ci<0){del=false;wi=(wi+1)%words.length}setTimeout(type,del?45:85)}type();
function complexityScore(){const vals=['service','scale','timeline','automation'].map(id=>$('#'+id)?.value||'');let s=30;if(vals[0].includes('AI')||vals[0].includes('Custom')||vals[0].includes('portal'))s+=22;if(vals[1].includes('Established'))s+=24;else if(vals[1].includes('Growing'))s+=14;if(vals[2].includes('Urgent'))s+=18;else if(vals[2].includes('Priority'))s+=8;if(vals[3].includes('Advanced'))s+=24;else if(vals[3].includes('Moderate'))s+=12;return Math.min(100,s)}
function updateEstimator(){const out=$('#estimatorResult');if(!out)return;const score=complexityScore();let level=score>75?'Strategic systems build':score>55?'Growth-focused digital build':'Professional launch build';let stack=score>75?'Recommended direction: custom architecture, integrations, automation workflows, analytics and a staged delivery roadmap.':score>55?'Recommended direction: premium website or web application with conversion-focused pages, automation touchpoints and reporting foundations.':'Recommended direction: high-quality responsive website with clear service pages, enquiry pathway, technical SEO and analytics foundations.';out.innerHTML=`<span class="pill">${level}</span><h3>${score}% project complexity</h3><p>${stack}</p><p><strong>Next step:</strong> book a consultation so the scope can be shaped around your business goals and required functionality.</p>`}['service','scale','timeline','automation'].forEach(id=>$('#'+id)?.addEventListener('change',updateEstimator));updateEstimator();
let step=0;const steps=$$('.form-step');function showStep(i){if(!steps.length)return;step=Math.max(0,Math.min(i,steps.length-1));steps.forEach((s,idx)=>s.classList.toggle('active',idx===step));const c=$('#stepCount');if(c)c.textContent=`${step+1} of ${steps.length}`}showStep(0);$$('[data-next]').forEach(b=>b.addEventListener('click',()=>showStep(step+1)));$$('[data-prev]').forEach(b=>b.addEventListener('click',()=>showStep(step-1)));
$('#leadForm')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const subject=encodeURIComponent('New project enquiry - Innovarian Tech Solutions');const body=encodeURIComponent(`Project type: ${data.get('projectType')||''}\nBusiness/Industry: ${data.get('businessType')||''}\nGoal: ${data.get('goal')||''}\nName: ${data.get('name')||''}\nEmail: ${data.get('email')||''}\nNotes: ${data.get('notes')||''}`);const res=$('#formResult');if(res){res.classList.remove('hidden');res.innerHTML='<h3>Thank you. Your enquiry is ready to send.</h3><p>Please send the prepared email, or contact us directly at info@innovariantechsolutions.com.</p>'}window.location.href=`mailto:info@innovariantechsolutions.com?subject=${subject}&body=${body}`});
$('#chatBtn')?.addEventListener('click',()=>$('#chat')?.classList.toggle('open'));
